Lint/named argument
duckie-team/duckie-quack-quack pull request #116
Opened 2022-09-16 10:44 UTC by limsaehyun

## 작업 사항
* NamedArgumentIssue 추가
* NamedArgumentTest 작성
* NamedArgumentDetector 구현

### 참고
 * 현재 이 규칙에서 호출되는 함수가 Composable인지 구별하는 방법은 아래와 같습니다.
 * 1. 컴포저블 안에서 invoke 돼야 함
 * 2. 호출되는 메서드의 함수가 대문자로 시작해야 함
 *
 * 이 방식은 Annotation으로 Composable을 구별하는 방식으로 개선해야 합니다.

2022-09-16 10:55 UTC, jisungbin reviewed
수고하셨어요!

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +private const val Explanation = "인자들을 쉽게 구별하기 위해 named argument는 필수적으로 사용해야 합니다."
```suggestion
private const val Explanation = "인자들을 쉽게 구별하기 위해 named argument 는 필수적으로 사용해야 합니다."
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> + * 2. 컴포저블 안에서 invoke 돼야 함
1 부터 시작되야 할 거 같아용

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> + * 1. function이 [IgnoredFunctions]인 경우
`[IgnoredFunctions]` 이 몬가요? 👀

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> + * 1. function이 [IgnoredFunctions]인 경우
한 줄 띄어주세요~~!

```suggestion
 * 다음과 같은 조건에서는 예외적으로 린트 에러가 발생하지 않습니다.
 
 * 1. function이 [IgnoredFunctions]인 경우
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +
```suggestion
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +            if (firstMethodName !in 'A'..'Z') return
[`Char.isUpperCase`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-upper-case.html) 있습니당
이거 써주시면 될 거 같아요!

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +            if (firstMethodName !in 'A'..'Z') return
이렇게 컴포저블 함수 구분하는게 최선일 거 같긴 하네요 ㅠㅠ
그냥 모든 곳에 named arguments 랑 trailing comma 적용하고 싶은데 마음 같아선,,, 그러면 코드가 오히려 더 더러워지는 일부 예외가 있다는게 참 아쉽네요 😢

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +
```suggestion
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +                    context.report(
```suggestion
                    return context.report(
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +                    return
```suggestion
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +    private fun ASTNode.isValueArgumentName() =
```suggestion
    private fun ASTNode.isValueArgumentName() = elementType == KtNodeTypes.VALUE_ARGUMENT_NAME
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +        this.elementType == VALUE_ARGUMENT_NAME
```suggestion
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +import org.jetbrains.kotlin.KtNodeTypes.VALUE_ARGUMENT_NAME
```suggestion
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/test/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentTest.kt
> + * 1. 컴포저블 함수여야 함
```suggestion
 *
 * 1. 컴포저블 함수여야 함
```

2022-09-16 10:55 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> + * 1. named argument를 사용해야 함
```suggestion
 * 1. named argument 를 적용하지 않음
```

2022-09-16 10:58 UTC, jisungbin commented
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/40740128/190624295-772be338-4261-4085-9571-9b2e9083e824.png">

코드 스타일 맞춰주세용

2022-09-16 13:20 UTC, jisungbin requested changes

2022-09-16 13:20 UTC, jisungbin commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> +    private fun ASTNode.isNotValueArgumentName() =
```suggestion
    private fun ASTNode.isNotValueArgumentName() = elementType != KtNodeTypes.VALUE_ARGUMENT_NAME
```

으로 바뀌어야 하는거 아닌가요? 👀 
지금처럼이라면 메서드 이름은 `VALUE_ARGUMENT_NAME` 가 아닌지 나타내는데 실제 구현은 `VALUE_ARGUMENT_NAME` 가 맞는지에요

2022-09-16 13:21 UTC, jisungbin commented
`DO NOT MERGE` 레이블 추가하셨길래 draft 로 바꿨슴니다

2022-09-17 13:41 UTC, jisungbin commented
@limsaehyun merge 준비되면 draft 풀어주시구 `Do Not Merge` label 제거해주세용

2022-09-18 10:28 UTC, jisungbin commented
@limsaehyun 제가 리팩토링 진행해서 머지해도 될까요?

2022-09-18 11:18 UTC, riflockle7 approved these changes

2022-09-18 11:18 UTC, riflockle7 commented on lint-compose/src/main/kotlin/team/duckie/quackquack/lint/compose/NamedArgumentDetector.kt
> + * */
맨 마지막 주석에 `*` 이 더 붙어있습니다.

2022-09-18 12:24 UTC, limsaehyun commented
https://sungbinland.slack.com/archives/C03TU31GSM7/p1663412630477969
해당 이슈로 인해 잠시 Do Not Merge 처리하겠습니다..

2022-10-07 20:34 UTC, jisungbin commented
## 예외가 너무 많아서 close

2022-10-07 20:34 UTC, closed without merging